name: Generate Snake

on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3  # Updated to v3

      # Generate the snake
      - uses: Platane/snk@v1.0  # Use a stable version instead of master
        id: snake-gif
        with:
          github_user_name: VeereshDodamani
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Show the status of the build for debugging
      - run: git status

      # Push the changes to the default branch (ensure it's 'main' or 'master')
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  # Use 'main' instead of 'master' (or keep 'master' if that's your default branch)
          force: true

      # Deploy to GitHub Pages from the 'dist' directory
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Ensure 'output' branch exists or this will fail
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
